trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - .config
    - .devcontainer
    - .github
    - .vscode
    - docs
    - .vsconfig
    - LICENSE.txt
    - logo.svg
    - README.md

pr:
- main

# build at least once a month so the build badge is up-to-date
schedules:
- cron: '0 0 1 * *'
  displayName: Monthly build
  branches:
    include:
    - main
  always: true

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  VersionSuffix: ''
  SkipSigning: false

pool:
  vmImage: windows-latest

steps:
- template: build/steps-ci.yml
- ${{ if eq(variables['Build.Reason'], 'Manual') }}:
  - template: build/steps-release.yml